### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by sunk818** [HelloZeroNet/ZeroNet#125] opened 2015-06-19 07:02 UTC
I get an unhandled exception when ZeroNet first starts up. I have a lot of sites I am trying to visit, especially the Mozilla Developer Network image. I think it choked on that, then I'm not sure what happened.

```
Starting ZeroNet/start.py...
- Starting ZeroNet...
[23:58:58] - Version: 0.3.1 r242, Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)], Gevent: 1.0.1
[23:58:58] - OpenSSL loaded, version: 01000201F
[23:58:58] - Creating UiServer....
[23:58:59] - Removing old SSL certs...
[23:58:59] - Creating FileServer....
[23:59:00] - Starting servers....
[23:59:00] Ui.UiServer --------------------------------------
[23:59:00] Ui.UiServer Web interface: http://127.0.0.1:43110/
[23:59:00] Ui.UiServer --------------------------------------
[23:59:00] - Opening browser: default_browser...
[23:59:02] FileServer Checking port 15441 using portchecker.co...
[23:59:02] FileServer [OK :)] Port open: Port 15441 is open.
[23:59:22] - Unhandled exception
Traceback (most recent call last):
  File "C:\temp\ZeroBundle-v0.1.0\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\temp\ZeroBundle-v0.1.0\ZeroBundle\ZeroNet\src\Connection\ConnectionServer.py", line 65, in handleIncomingConnection
    connection.handleIncomingConnection(sock)
  File "C:\temp\ZeroBundle-v0.1.0\ZeroBundle\ZeroNet\src\Connection\Connection.py", line 90, in handleIncomingConnection
    if sock.recv( 1, gevent.socket.MSG_PEEK ) == "\x16":
  File "C:\temp\ZeroBundle-v0.1.0\ZeroBundle\Python\lib\site-packages\gevent\socket.py", line 385, in recv
    return sock.recv(*args)
error: [Errno 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "C:\temp\ZeroBundle-v0.1.0\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\temp\ZeroBundle-v0.1.0\ZeroBundle\ZeroNet\src\Connection\ConnectionServer.py", line 65, in handleIncomingConnection
    connection.handleIncomingConnection(sock)
  File "C:\temp\ZeroBundle-v0.1.0\ZeroBundle\ZeroNet\src\Connection\Connection.py", line 90, in handleIncomingConnection
    if sock.recv( 1, gevent.socket.MSG_PEEK ) == "\x16":
  File "C:\temp\ZeroBundle-v0.1.0\ZeroBundle\Python\lib\site-packages\gevent\socket.py", line 385, in recv
    return sock.recv(*args)
socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host
```

**Comment by HelloZeroNet** [comment] 2015-06-19 10:28
Thanks for reporting, I was unable to reproduce it, but probably fixed by 1f53212d62ae7202c6b8efdbe84e94b745663471
Please reopen the issue if you still have problems after updating.

**Closed by HelloZeroNet** 2015-06-19 10:28 UTC

**Comment by sunk818** [comment] 2015-06-19 16:05
Hopefully, I can figure out how to apply the new code to the existing ZeroBundle. I take it the ZeroBundle is not part of the GitHub zip file, so I have take ZeroNet-master.zip and merge it with the existing files...?

**Comment by HelloZeroNet** [comment] 2015-06-19 16:27
You have some options:
 - Download the https://github.com/HelloZeroNet/ZeroNet/archive/master.zip file, unpack to current dir and overwrite current files
 - Using file explorer in your Zeronet directory (where you have an update.py): File > Open Command prompt then enter `..\Python\python.exe update.py`
 - Rename your ZeroNet directory and execute start.cmd again. It downloads the latest version from github. Overwrite the data directory from your previous installation to have the same identity, sites and settings.
