### ISSUE TITLE
Faild to startup ZeroNet from desktop at system startup (The system can not find the ZeroNet.exe file)

### ISSUE THREAD

**Issue by mx5kevin** [HelloZeroNet/ZeroNet#2429] opened 2020-02-19 16:30 UTC
### Step 1: Please describe your environment

 

  * ZeroNet version: 0.7.1 (rev4445)

  * Operating system: Windows 10 Enterprise

  * Web browser: Firefox 72.02

  * Tor status: always

  * Opened port: no

  * Special configuration: Run ZeroNet client at sytem startup when windows start. And installed the ZeroNet folder to the desktop.

 

### Step 2: Describe the problem:

 

In the Drive C ZeroNet works perfectly. In the desktop in startup i got a msg (the system can not find ZeroNet.exe file). If i start my self the file ZeroNet are running. When the system try to start at sytem startup i got this error msg.

 

#### Steps to reproduce:

 

Extract the complete ZeroNet folder to desktop. The current user directory cointans special characters ÁŐÚŰ.Setup Start ZeroNet when Windows starts option. Reboot the computer.

 

#### Observed Results:

 

I got a error msg after system startup and ZeroNet faild to start. (The system can not find the ZeroNet.exe file.)

 

#### Expected Results:

 

Older py 2 versions didn't have that problem. All py3 version this problem occurs. It worked well on the same computer for a long time.

**Comment by HelloZeroNet** [comment] 2020-02-19 17:39
Thanks I was able to reproduce the problem. There is also issue starting/shutting down the Tor client from directory with special chars

Working on the fix

**Comment by HelloZeroNet** [comment] 2020-02-19 18:39
Looks like the tor windows client has problems with utf8 characters in directories as the official python lib also have problem connecting issue. I have opened an issue for it: https://github.com/torproject/stem/issues/57

**Comment by HelloZeroNet** [comment] 2020-02-20 17:31
The startup problem should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/fca1033f83e9b82e94733e1e7452bf88f61cc377

Tor still might have problems authenicating from some special directories, because the tor client utf8 encoding looks broken and some characters encoded differently (from hungarian chars it encodes `û` instead of `ű` and `õ` instead of `ő`)

**Comment by HelloZeroNet** [comment] 2020-02-26 17:24
Workaround for Tor client bug: https://github.com/HelloZeroNet/ZeroNet/commit/b85477787dddaf1e485ac7511059b578ae155b32 added in Rev4458

**Closed as completed by HelloZeroNet** 2020-02-26 17:24 UTC
Labels: bug
