### ISSUE TITLE
Site content.json load error: ProgrammingError: Recursive use of cursors not allowed.

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2323] opened 2019-11-22 10:28 UTC
### Step 1: Please describe your environment

  * ZeroNet version: rev4290
  * Operating system: W10
  * Web browser: FF beta
  * Tor status: available

### Step 2: Describe the problem:

I am updating zeronet every a few days. In last maybe 2-4 days i found Zeronet to crash at least 2 times. I mean process is not running. Today i checked the error.log which was empty and last line in debug.log was:

> [2019-11-22 ***] ERROR    Site:1ADQAH..g6aA Json data/users/mypublickeyhere/content.json load error: ProgrammingError: Recursive use of cursors not allowed. in SiteStorage.py line 342 > ContentFilter/ContentFilterPlugin.py line 180 > SiteStorage.py line 101 > Db.py line 364 > DbCursor.py line 192 > DbCursor.py line 103

(ZN tried to publish new comment on that site. But on re-start publishing same or similar comment in same place on that site seem to work)
In previous sessions, debug log files does not contain any errors at the end of files.

**Comment by HelloZeroNet** [comment] 2019-11-25 13:59
Thanks for reporting, I was able to reproduce similar problem and it should be fixed by: #2323

**Comment by slrslr** [comment] 2019-11-26 18:36
@HelloZeroNet 
today i was running rev4303 on Windows10 and i seen similar error like one described in this issue above. Here is the error i got under rev4303:

> [2019-11-26 \*\*\*] ERROR    Site:18Pfr2..pSzh WebSocket handleRequest error: ProgrammingError: Recursive use of cursors not allowed. in UiWebsocket.py line 79 > UiWebsocket.py line 232 > OptionalManager/UiWebsocketPlugin.py line 163 
>  {"cmd":"optionalFileList","params":{"filter":"","address":"18Pfr2oswXvD352BbJvo59gZ3GbdbipSzh","limit":1000},"wrapper_nonce":"\*\*\*","id":7}

i remember that on that site i clicked Seed file button, clicked some video in "Up next" sidebar of the site that appears when playing a video.

one hour later, zeronet process silently crashed (disappeared) and above mentioned log line was the last ERROR line in the file, rest was just INFO. error.log was empty..

**Comment by HelloZeroNet** [comment] 2019-11-26 19:14
Thanks, I was able to reproduce the error this time:
Looks like it happens the cursor and the returned result processor is in separate threads.
Working on the fix...

**Comment by HelloZeroNet** [comment] 2019-11-27 02:15
I have added a new modification that should fix this issue according to my test: https://github.com/HelloZeroNet/ZeroNet/commit/fca9db7972f17cca568bcaaac95159e0273609f6

Please update to Rev4308 to see if it's fixed for you.

**Comment by HelloZeroNet** [comment] 2019-12-30 16:57
It should be fixed in the lastest rev

**Closed as completed by HelloZeroNet** 2019-12-30 16:57 UTC
Labels: bug
