### ISSUE TITLE
bug in zero hello in safari 

### ISSUE THREAD

**Issue by iShift** [HelloZeroNet/ZeroNet#268] opened 2016-02-12 13:25 UTC
If you have site with long name - you can't delete them, example: 
http://127.0.0.1:43110/1AQj7DF45w5DK2Ga486YT8QaYhpedgE5tR
![2016-02-12 16 23 57](https://cloud.githubusercontent.com/assets/426427/13008055/2f53272a-d1a5-11e5-8d1a-a73d583f1cf3.png)
![2016-02-12 16 23 52](https://cloud.githubusercontent.com/assets/426427/13008056/2f7bded6-d1a5-11e5-9c6b-3049b5929591.png)

**Comment by HelloZeroNet** [comment] 2016-02-12 13:29
Can't reproduce it under Win/FF/Chrome/IE yet

**Comment by iShift** [comment] 2016-02-12 13:56
hmm, only safari bug.

**Comment by HelloZeroNet** [comment] 2016-02-18 11:02
Fixed in the latest version

**Closed by HelloZeroNet** 2016-02-18 11:02 UTC
