### ISSUE TITLE
audit torrent implementation for IP leaks

### ISSUE THREAD

**Issue by adrelanos** [HelloZeroNet/ZeroNet#274] opened 2016-02-20 14:38 UTC
I understand, ZeroNet internally uses torrent.

Have you seen the following paper?

Bittorrent over Tor isn't a good idea
- https://blog.torproject.org/blog/bittorrent-over-tor-isnt-good-idea
- http://hal.inria.fr/docs/00/47/15/56/PDF/TorBT.pdf

Torrent clients (libraries) use socks proxy settings for connectivity. Not anonymity. The threat in essence boils down to torrent clients using fancy techniques (similar to "sudo ifconfig"), finding out their real external clearnet IP, and then sending that IP through the proxy.

Connection from Tor exit coming and including the information "hi, my real name is...".

Are you sure, that zeronet's usage of torrent does not suffer from the same issue?

**Comment by TheNain38** [comment] 2016-02-20 14:39
It uses .onion HS to communicate

**Comment by adrelanos** [comment] 2016-02-20 14:40
What in case only Tor proxy settings without Tor ControlPort - hence without Tor hidden services?

**Comment by HelloZeroNet** [comment] 2016-02-20 16:05
ZeroNet protocol is totally different from bittorrent, so it's not an issue here.

**Comment by maxogden** [comment] 2016-03-02 22:36
@adrelanos from what I understand ZeroNet relies on BitTorrent Trackers for peer discovery, which means the ips, ports and hashes being advertised by ZeroNet clients can be leaked from any of the Trackers (due to the tracker scrape API)

**Comment by HelloZeroNet** [comment] 2016-03-02 22:39
ips are not leaked when connecting to trackers, it uses the exit node ip

**Comment by maxogden** [comment] 2016-03-02 22:44
@HelloZeroNet but torrent trackers themselves leak IPs and hashes, which from a mass surveillance standpoint might make deanonymizing users easier. Is there any security threat model documentation on ZeroNet available?

**Comment by HelloZeroNet** [comment] 2016-03-02 22:53
The trackers also requested using the exit nodes, so i think it's not an issue

**Comment by maxogden** [comment] 2016-03-02 23:13
@HelloZeroNet one attack I can think of off the top of my head for example is:

- I use the tracker scrape API on these https://github.com/HelloZeroNet/ZeroNet/blob/779075c4a56ef921f4095220725a16b156eba52e/src/Config.py#L33
- Now I know the IPs of all the tor exit nodes of ZeroNet users (and the sha1 of their site addresses)
- If I want to prevent a specific user from being able to discover peers I can DDOS announces to the tracker they are using which will bump them from the LRU resulting in them never being announced to other peers because mine will probabilistically win

**Comment by border0464111** [comment] 2017-04-14 20:49
hummm it could make sense , Can you build a reproductible ProofOfConcept for this attack ?

**Comment by purplesyringa** [comment] 2020-03-03 18:32
@HelloZeroNet As there are no IP leaks (most likely) and the availability problem can't be solved, can we close the issue?

**Comment by adrelanos** [comment] 2020-03-04 06:22
Did anyone read the references which I posted in the original post?

* https://blog.torproject.org/blog/bittorrent-over-tor-isnt-good-idea
* http://hal.inria.fr/docs/00/47/15/56/PDF/TorBT.pdf

The issue isn't a direct clearnet connection (without proxy) to a destination.
It's about telling the destination the originating IP address through the protocol / data contents.
Similar to sending an e-mail over Tor saying "my real IP is x.x.x.x". The transmission perfectly over Tor but the contents are the problem.

**Comment by purplesyringa** [comment] 2020-03-04 10:14
I did. We don't send IPs AFAIK.

**Comment by HelloZeroNet** [comment] 2020-03-04 16:35
The information that we send: https://github.com/HelloZeroNet/ZeroNet/blob/py3/src/Connection/Connection.py#L364

The target_ip is the address of the destination connection. It's required when you have multiple onion services that points to the same port.

**Closed by HelloZeroNet** 2020-03-04 16:35 UTC
