### ISSUE TITLE
Add Possibility to download ZeroNet from within ZeroNet :)

### ISSUE THREAD

**Issue by Richard87** [HelloZeroNet/ZeroNet#468] opened 2016-05-25 21:38 UTC
The title sais it all actually, I think the dashboard should contain a link, so everyone hosting a proxy would keep zeronet source also distributed :)

Richard

**Comment by EtherTyper** [comment] 2016-05-26 01:03
See #416. This is a hot subject, and the reason the implemented the gogs.io and GitLab mirrors.

**Comment by border0464111** [comment] 2017-05-11 15:52
Duplicate of the closed https://github.com/HelloZeroNet/ZeroNet/issues/416 issue.   
Closing?

**Closed** 2017-05-14 20:20 UTC
