### ISSUE TITLE
Allow Javascript

### ISSUE THREAD

**Issue by alanlu776** [HelloZeroNet/ZeroNet#182] opened 2015-10-11 06:58 UTC
JavaScript buttons lead to an error in ZeroNet.

**Comment by HelloZeroNet** [comment] 2015-10-11 09:35
Please be more specific

**Comment by gaapt** [comment] 2015-10-12 08:22
Are you using Tor?

**Comment by alanlu776** [comment] 2015-10-12 08:46
I don't think Tor would change much about the JavaScript, and HelloZeroNet, I was referring to creating a blog, when you've duplicated one of the defaults and clicking the edit button. In the box, you can the type up a simple HTML webpage, and this is when the JavaScript causes problems. When I made a function to create a simple alert, the blog displayed an error and locked me out. I was then not able to edit the box that I was originally editing, but the title and the description were all editable.

**Comment by HelloZeroNet** [comment] 2015-10-12 10:37
What os/browser are you using?

**Comment by alanlu776** [comment] 2015-10-13 04:59
My user agent string is: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36 and for more information you can visit http://whatsmybrowser.org/b/CGNSQEI

**Comment by TheNain38** [comment] 2016-01-16 14:13
Is anyone having the same problem?

**Comment by border0464111** [comment] 2017-04-15 16:07
I can't reproduce and OP did not provide any ProofOfConcept 
Closing ?

**Closed** 2017-04-16 10:20 UTC
