### ISSUE TITLE
Please provide a zeronet.desktop and zeronet.png file for Linux

### ISSUE THREAD

**Issue by probonopd** [HelloZeroNet/ZeroNet#831] opened 2017-02-12 23:20 UTC
Please provide a [zeronet.desktop](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) and zeronet.png file for Linux desktop integration.

Ideally also an [AppStream metainfo file](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html).

This would allow packagers for Linux to use consistent menu launchers, icons, and metadata, and help [here](https://github.com/HelloZeroNet/ZeroNet/issues/283).
Thanks!

**Comment by border0464111** [comment] 2017-04-14 21:01
This issue would belong in zeroBundle repository more then here, also PR are always a strong argument to  make improvement  :D

**Comment by border0464111** [comment] 2017-04-14 21:01
duplicate of https://github.com/HelloZeroNet/ZeroNet/issues/283

**Closed** 2017-04-14 23:02 UTC

**Comment by probonopd** [comment] 2017-04-15 07:29
@border0464111 no this is not a duplicate of #283. This ticket here is about the missing desktop and icon file, which has nothing to do with AppImage specifically, but which every Linux application should provide according to the https://standards.freedesktop.org/desktop-entry-spec/latest/. Please repoen.

**Comment by border0464111** [comment] 2017-04-15 14:40
Oh my bad, I tough providing a png image and icon was a subtask of building an appImage. 

But indeed it can be use in different others context. 

I reopend the issue on bundle repository: https://github.com/HelloZeroNet/ZeroBundle/issues/18
