### ISSUE TITLE
Server error if Multiuser plugins is enabled

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#1107] opened 2017-09-02 07:49 UTC
Err: AttributeError: 'list' object has no attribute 'next' in UiServer.py line 94 > UiRequest.py line 116 > MutePlugin.py line 138 > MultiuserPlugin.py line 62
Details:
```
{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate, br", 
    "HTTP_ACCEPT_LANGUAGE": "zh-CN,zh;q=0.8", 
    "HTTP_HOST": "fuckcf.cf", 
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1", 
    "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3198.0 Safari/537.36", 
    "HTTP_X_FORWARDED_FOR": "111.3.58.227", 
    "HTTP_X_FORWARDED_PROTO": "https", 
    "HTTP_X_REAL_IP": "111.3.58.227", 
    "PATH_INFO": "/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
    "QUERY_STRING": "", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "33590", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "localhost", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.0 Python/2.7", 
    "arguments": {
        "action": "main", 
        "batch": false, 
        "bind": null, 
        "bit_resolver": "1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F", 
        "coffeescript_compiler": null, 
        "config_file": "zeronet.conf", 
        "connected_limit": 8, 
        "data_dir": "data", 
        "db_mode": "speed", 
        "debug": false, 
        "debug_gevent": false, 
        "debug_socket": false, 
        "disable_db": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "download_optional": "manual", 
        "end": true, 
        "file_size_limit": 10, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "fix_float_decimals": false, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "ip_local": [
            "127.0.0.1"
        ], 
        "keep_ssl_cert": false, 
        "language": "zh", 
        "log_dir": "log", 
        "max_files_opened": 2048, 
        "msgpack_purepython": false, 
        "multiuser_local": false, 
        "multiuser_no_new_sites": false, 
        "open_browser": null, 
        "optional_limit": "10", 
        "proxy": null, 
        "silent": false, 
        "size_limit": 10, 
        "stack_size": null, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_hs_limit": 10, 
        "tor_proxy": "127.0.0.1:9050", 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.opentrackr.org:1337/announce", 
            "http://explodie.org:6969/announce", 
            "http://tracker1.wasabii.com.tw:6969/announce"
        ], 
        "trackers_file": false, 
        "ui_host": [
            "fuckcf.cf"
        ], 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "updatesite": "1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp", 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false, 
        "workers": 5
    }, 
    "plugins": [
        "AnnounceZero", 
        "Cors", 
        "CryptMessage", 
        "FilePack", 
        "MergerSite", 
        "Multiuser", 
        "Mute", 
        "Newsfeed", 
        "OptionalManager", 
        "PeerDb", 
        "Sidebar", 
        "Stats", 
        "TranslateSite", 
        "Trayicon", 
        "Zeroname"
    ], 
    "version_gevent": "1.0.2", 
    "version_python": "2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]", 
    "version_zeronet": "0.5.7 r2187", 
    "wsgi.url_scheme": "http"
}
```
I removed all files in `data`, but the error occurred again.

**Comment by grez911** [comment] 2017-09-02 09:00
@HelloZeroNet Problem has been confirmed, I just cloned clean repo, renamed disabled-Multiuser to Multiuser, launched zeronet and got the exact error.

**Comment by HelloZeroNet** [comment] 2017-09-02 12:31
Thanks for reporting, fixed in: https://github.com/HelloZeroNet/ZeroNet/commit/bfd3d18a10e3cceddf88946dd4567e51acfd7200

**Closed by HelloZeroNet** 2017-09-02 12:31 UTC
Labels: bug

**Comment by grez911** [comment] 2017-09-02 12:35
@HelloZeroNet I'm so sorry, because I created this bug.

**Comment by HelloZeroNet** [comment] 2017-09-02 13:03
@grez911 No probs, at least we know why is it necessary :)
