### ISSUE TITLE
Publish ZeroNet Installer to Torrent Websites

### ISSUE THREAD

**Issue by jesseray** [HelloZeroNet/ZeroNet#416] opened 2016-04-12 08:33 UTC
I mentioned in Issue #415 that I wanted to share Lantern on my ZeroNet site to help fight censorship. However, someone pointed out at a glaring flaw in my thinking: they would need to be able to download ZeroNet, which is on Github, which is blocked by China. In essence, China has blocked access to ZeroNet and thus blocked people from downloading Lantern from me. Doh!

The problem? The ZeroNet installer is provided in a centralized way. This could be addressed by having an automated system that creates a torrent of the latest version of ZeroNet and then publishes that torrent to various torrenting websites. You can check whether a torrenting website (or any website, really) has been blocked by China by using this website: http://www.blockedinchina.net/. I have already checked http://kat.cr and it was not blocked.

**Comment by HelloZeroNet** [comment] 2016-04-12 08:54
According to wikipeda github is safe: "On January 21, 2013, GitHub was blocked in China using DNS hijacking. Confirming the block, a spokesperson for GitHub said: "It does appear that we’re at least being partly blocked by the Great Firewall of China".[a][7] The block was lifted on January 23, 2013 after an online protest on Sina Weibo." - https://en.wikipedia.org/wiki/Censorship_of_GitHub

I have created mirrors:
 - https://gitlab.com/HelloZeroNet/ZeroBundle/tree/master/dist
 - https://try.gogs.io/ZeroNet/ZeroBundle/src/master/dist

**Comment by icf20** [comment] 2016-04-16 17:04
you can use https://en.greatfire.org/https/github.com to see if is blocked or not

**Comment by border0464111** [comment] 2017-05-11 14:55
Prior to this we would need @nofish to sign releases. Then copy could be shared accross zeronet by zeronet site owner and validated aganst key. 

As soon As we will have this, I would be available to contribute time to create a zeronet site with all the releases .zip

**Comment by HelloZeroNet** [comment] 2017-05-11 15:07
Actually the source code already on ZeroNet site: 1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp and if you have this site your client will use this to update your client instead of https source.

**Comment by border0464111** [comment] 2017-05-11 15:13
Oh, cool. 

So everything concerning this issue have been done/solvec already ?

**Comment by purplesyringa** [comment] 2020-03-03 18:41
Given that the problem is resolved, can we close the issue? @HelloZeroNet

**Closed** 2020-03-04 17:11 UTC
