### ISSUE TITLE
content.json load error: Exception: dbschema.json is not a valid JSON: Worker stopped in core/src/Site/SiteStorage.py line 363 > ContentFilter/ContentFilterPlugin.py line 180 > core/src/Site/SiteStorage.py line 115 > ... > 72

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2411] opened 2020-02-06 13:35 UTC
### Step 1: Please describe your environment

  * ZeroNet version: 4399
  * Operating system: W10
  * Web browser: FF beta

### Step 2: Describe the problem:

Error in debug.log
ERROR    Site:1ADQAH..g6aA Json data/users/1BfmL3LMTZQ9qPyqTRVfTy9LCnyLHmc1kP/content.json load error: Exception: dbschema.json is not a valid JSON: Worker stopped in core/src/Site/SiteStorage.py line 363 > ContentFilter/ContentFilterPlugin.py line 180 > core/src/Site/SiteStorage.py line 115 > ... > 72

content.json and data.json files if needed are [here](https://gofile.io/?c=3q2Pwy) (pass word: aaaaaa)

**Comment by purplesyringa** [comment] 2020-02-06 14:06
Can you please attach dbschema.json of the site please?

**Comment by slrslr** [comment] 2020-02-06 14:10
@imachug
[dbschema.json here](https://pastebin.com/raw/VUYK49cP)

**Comment by purplesyringa** [comment] 2020-02-06 14:14
Sorry @slrslr, could you please upload data.json & content.json once again? They are most likely not required but it looks like they are missing now.

**Comment by purplesyringa** [comment] 2020-02-06 14:19
Were there any other lines containing "Worker stopped" nearby in debug.log?

**Comment by slrslr** [comment] 2020-02-06 14:35
i updated the link my first post and there is no other line containing "Worker stopped"

**Comment by HelloZeroNet** [comment] 2020-02-06 17:09
The content.json & dbchema.json looks good, so I think it happened, because the db creation/load was called during the dbschema.json write. The file was created, but the content write was incompete.

Currently it only checks if the dbschema.json file is exist or not: https://github.com/HelloZeroNet/ZeroNet/blob/py3/src/Site/SiteStorage.py#L50

**Comment by HelloZeroNet** [comment] 2020-02-07 16:41
I was unable to reproduce it, but I think it should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/8e79a7da635e4a9ed028571c3b7e82d3c86fef24 in Rev4404

It would be great to find a way to emulate slow file reads.

**Closed as completed by HelloZeroNet** 2020-02-07 16:41 UTC
Labels: bug
