### ISSUE TITLE
[Question] Can run more than one ZeroNet instance?

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1653] opened 2018-09-23 15:55 UTC

**Comment by imachug** [comment] 2018-09-23 16:03
It can if you set different data folders and port (via CLI arguments).

**Comment by DaniellMesquita** [comment] 2018-09-23 16:27
But isn't uiserver to make it accessible via LAN?

**Comment by imachug** [comment] 2018-09-23 16:29
No, it's `fileserver`.

**Comment by DaniellMesquita** [comment] 2018-09-23 16:32
What port you recommend? That is less probably to be used.

**Comment by imachug** [comment] 2018-09-23 16:37
`7832`.

**Comment by leftside2** [comment] 2018-09-24 00:43
Do we need a kind of the duplicate of the Zeronet directories, or just execute the same zeronet.py?

**Comment by DaniellMesquita** [comment] 2018-09-24 02:05
I'm asking this because I'll create a app framework for ZeroNet based on Electron/Cordova, for dedicated apps (replacing ZeroHello to the app zite, and only storing ID providers.

**Comment by blurHY** [comment] 2018-09-24 02:08
It just needs different ui-server and file-server port

**Comment by leftside2** [comment] 2018-09-24 04:10
@blurHY , Any possibility to have different tor IP address for each instance??

**Comment by leftside2** [comment] 2018-09-24 04:14
My main process : $ ./ZeroNet.sh --tor always --tor_controller 127.0.0.1:9151;
error msg: None.

Additional instance : $ ./ZeroNet.sh --ui_port=8090;
error msg: Can't open lock file, your ZeroNet client is probably already running, exiting... ([Errno 11] Resource temporarily unavailable)

**Comment by blurHY** [comment] 2018-09-24 04:49
You need two zeronet folders

**Comment by leftside2** [comment] 2018-09-24 04:55
@blurHY , that's the answer what I wanted! :100:

**Comment by HelloZeroNet** [comment] 2018-10-02 16:44
You can, but you need to specify unique values for data_dir, log_dir, fileserver_port, uiserver_port

**Closed by HelloZeroNet** 2018-10-02 16:44 UTC

**Comment by DaniellMesquita** [comment] 2018-10-02 16:48
Why need to specify data_dir, log_dir, if ZeroNet instance could detect from which folder it is running?

**Comment by DaniellMesquita** [comment] 2018-10-02 16:49
Also, when detecting that another instance is running, run in fileserver/uiserver ports with increased number.

**Comment by HelloZeroNet** [comment] 2018-10-02 17:10
Changing data_dir and log_dir is only necessary if you try to run it from the same directory (using the same binary). I think silently running it on different port would be a bad idea as most of the users don't want to run multiple instances.
