### ISSUE TITLE
User is unable to proceed to site if address is SHA-256 summed on blocklist.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2572] opened 2020-06-02 13:58 UTC
Instead, the user has to go back and disable the blocklist, then revisit the blocked site's link. This is inconvenient.

**Comment by HelloZeroNet** [comment] 2020-06-18 17:06
I was unable to reproduce the bug, what I did:

 - Added a site to a shared blocklist using it's sha256 encoded address
 - Visited the site
 - Clicked on "Remove from blocklist and visit the site" button
 - The site got loaded

What does happens to you when you do the same?

**Comment by styromaniac** [comment] 2020-06-18 18:30
It's no longer an issue.

**Comment by styromaniac** [comment] 2020-06-21 14:53
The Linux laptop on 4493 can't proceed to the site.

Internal error: AttributeError("'NoneType' object has no attribute 'get'"): 'NoneType' object has no attribute 'get'
UiWebsocket.py line 79 > 239 > ContentFilter/ContentFilterPlugin.py line 128 > ContentFilter/ContentFilterStorage.py line 140

**Comment by HelloZeroNet** [comment] 2020-06-30 16:04
It's fixed by https://github.com/HelloZeroNet/ZeroNet/commit/635c3b27cd195988dac1ca53a0de3821fa07d36b in Rev4496

Actually it was not related to hashed site address blocks, but it happened if you followed a list that does not had "siteblocks" node in the json.

**Closed as completed by HelloZeroNet** 2020-06-30 16:04 UTC
Labels: bug
