### ISSUE TITLE
Cross-OS issue, pages not loaded -> empty page

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1313] opened 2018-03-03 13:14 UTC
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2 rev3340
  * Operating system: Win. 10 & Linux Ubuntu
  * Web browser: Firefox
  * Tor status: error and or Available
  * Opened port: yes
  * Special configuration: OpenVPN used

#### Steps to reproduce:

  1. open [this zite](http://127.0.0.1:43110/1Kt7xxVRcxHcK14Mt7YZdXfh8MzUJMkvpk/) and find "How to stream"
  2. click that link
  3. see the empty page. But now refresh (F5) page, and page will load properly

Firefox dev. console (F12) says:

[ZeroWebsocket] Closed 
close
bubbles: false
cancelBubble: false
cancelable: false
code: 1006
composed: false
currentTarget: null
defaultPrevented: false
eventPhase: 0
explicitOriginalTarget: WebSocket { url: "ws://127.0.0.1:43110/Websocket?wrapper_key=keyhereireplaced", readyState: 3, bufferedAmount: 0, … }
isTrusted: true
originalTarget: WebSocket { url: "ws://127.0.0.1:43110/Websocket?wrapper_key=keyhereireplaced", readyState: 3, bufferedAmount: 0, … }
reason: ""
target: WebSocket { url: "ws://127.0.0.1:43110/Websocket?wrapper_key=keyhereireplaced", readyState: 3, bufferedAmount: 0, … }
timeStamp: 76193.494406
type: "close"
wasClean: false
__proto__: CloseEventPrototype { wasClean: Getter, code: Getter, reason: Getter, … }
all.js:143:14

This happen in my case on various sites since roughly last 5-14 days maybe. Also i was seeing wrapper_nonce kind of error and empty page on ZeroHello if it can be related somehow.

I hope this is fixed soon as it hurt experience quite significantly.

**Comment by krixano** [comment] 2018-03-03 17:42
I'm having a similar problem. It's not related to wrapper_nonce being in the url. For example, I would click on a Git Center repo in it's repository index, and a blank page would show. I would have to refresh to see the blank page. This happens to at least one other site, I think it was ZeroNet Docs.

I'm on Firefox and Linux. No special configuration, no Tor, and rev3337.

**Comment by HelloZeroNet** [comment] 2018-03-04 09:16
I was able to reproduce the bug. Looking for fix.

**Comment by HelloZeroNet** [comment] 2018-03-08 10:44
It should be fixed in Rev3351, https://github.com/HelloZeroNet/ZeroNet/commit/e96dd14e0d0de7abe9ef87c48dac1c2366817be1
please update and see if it's works for you

**Closed by HelloZeroNet** 2018-03-08 10:44 UTC
Labels: bug

**Comment by slrslr** [comment] 2018-03-08 11:11
Yes, i confirm it works. Thank you for fixing it.

**Comment by slrslr** [comment] 2018-03-08 22:00
@HelloZeroNet and on [this zite](http://127.0.0.1:43110/yingsuo.bit) when i click "客户端&教程" i see blank page and Firefox dev. console says on it: "Load denied by X-Frame-Options: http://127.0.0.1:43110/yingsuo.bit/help.html?wrapper_nonce=*** does not permit cross-origin framing."

**Comment by slrslr** [comment] 2018-03-09 18:30
@HelloZeroNet hello, i spot the issue on other zite, please open ZeroVoat
and then open some topic/question
wait until it load and then click browser back button.
It do not complete loading and Firefox dev. console says:
"SecurityError: Permission denied to access property "toString" on cross-origin object"

**Comment by HelloZeroNet** [comment] 2018-03-09 18:56
as for http://127.0.0.1:43110/yingsuo.bit: opening to new window does not works with zeronet sites
as for zerovoat: i cant reproduce it
